# Generated by Django 4.0.5 on 2022-07-11 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Patente')),
                ('chofer', models.CharField(max_length=20, verbose_name='Chofer')),
                ('modelo', models.CharField(max_length=30, verbose_name='Modelo')),
                ('ubicacionsal', models.CharField(max_length=40, verbose_name='Ubicacion_Salida')),
                ('disponibilidad', models.CharField(max_length=10, verbose_name='Disponibilidad')),
                ('cantdisponible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAeropuerto.categoria')),
            ],
        ),
    ]
