# Generated by Django 4.0.5 on 2022-07-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAeropuerto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='disponibilidad',
        ),
    ]
